### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by julienym**
I wanted to test quickly this stack, so I've created a working docker image and docker-compose (openl2m+postgres). There would be much more love to add, but it's a first step and I need to find of my switches will works (snmp)...

Somes notes:
- I've noted that Python3.8 (from Ubuntu apt install) throws structure errors, but works fine with 3.10 (tested with Ubuntu 22.04 Python 3.10.12)
- tzdata was missing
- If not everything seams to work fine, except that I could'nt automate the superuser creation

Build with docker-compose build and run with docker-compose up

### CODE REVIEW

**Comment by johanreinalda** [comment]
Thanks for this PR. I just took a look at your PR, and noted a few things (note I am not a docker specialist, so some of this may be incorrect). This is based on OpenL2M v3.1, just pushed publicly to the development branch (main will come next week)
- this runs the Django 'test' web server. Great for development and test, not for production.
- the new v3.1 code runs Django 5, which requires python 3.10 or higher. From what I see, that will not work as is. I am not sure how to fix that.

That being said, i am interested in this work, as it has been on our (long term) wish list. We could include this for development purposes (once it will run v3.1) and then work on a different config that includes nginx for production...

Thoughts?

**Comment by johanreinalda** [comment]
To test, I just pulled this PR into a new branch and merged with "development". Then ran "docker-compose up", and I get the following error:

Step 8/10 : ADD --chown=openl2m entrypoint.sh .
ERROR: Service 'openl2m' failed to build : ADD failed: file not found in build context or excluded by .dockerignore: stat entrypoint.sh: file does not exist

"entrypoint.sh" is referenced in Dockerfile, but does not exist?

This is on Ubuntu 20.04, running docker-ce 5:25.0.3

**Comment by julienym** [comment]
> "entrypoint.sh" is referenced in Dockerfile, but does not exist?

@johanreinalda Sorry I didn't notice, it was in .gitignore, I've just added it

**Comment by johanreinalda** [comment]
got it running. I noticed it keeps the login session open (ie does not run in background, and the shell.)

I have no idea how to get the admin account created. I tried uncommenting code in entrypoint.sh, and a few versions of command line 
"docker compose exec openl2m /opt/openl2m/openl2m/manage.py createsuperuser"
Could not get anything to take. I am showing my lack of docker skills (I have a few containers running, but all open source from others :-) )

Maybe the netbox code may help here.... (https://github.com/netbox-community/netbox-docker)

**Comment by julienym** [comment]
> got it running. I noticed it keeps the login session open (ie does not run in background, and the shell.)
> 
> I have no idea how to get the admin account created. I tried uncommenting code in entrypoint.sh, and a few versions of command line "docker compose exec openl2m /opt/openl2m/openl2m/manage.py createsuperuser" Could not get anything to take. I am showing my lack of docker skills (I have a few containers running, but all open source from others :-) )
> 
> Maybe the netbox code may help here.... (https://github.com/netbox-community/netbox-docker)

Hey @johanreinalda, some tips:
- to run it in background docker-compose up **-d** OR docker-compose up **&** (that will let you see the logs while opening it in the "background")
- to shut it down: docker-compose down (add -v to delete volume to do a fresh reset)
- i couldn't create the user auto. so so you have to exec in and run the command:
  -  docker exec -ti openl2m-openl2m-1 bash
  - then run you're python command to create the user

**Comment by johanreinalda** [comment]
I got all this working. I am merging this in, and moving to a sub-directory "docker/test" since this is not production-ready containerization. I will also add some documentation, and then release it with the 3.1.x line...
Thanks for the work!

**Pull request merged**
